services:
  - type: web
    name: bird-species-classifier
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app  # Replace with your actual start command
